// GENERATED by tools/export_model.py -- do not edit by hand.
//
// Fitted on the Chicago Face Database: 823 neutral faces for the
// canonical template, 307 neutral->smile pairs from 153
// identities for the smile axis. No image data is reproduced here, only
// aggregate geometry.

/** Canonical rigid-anchor positions, in interpupillary units. Keyed by
 *  MediaPipe landmark index so ordering cannot drift between languages. */
export const CANONICAL_TEMPLATE: ReadonlyArray<readonly [number, readonly [number, number]]> = [
  [1, [0.001627, 0.538550]],
  [6, [0.000335, -0.010455]],
  [8, [-0.002881, -0.254551]],
  [33, [-0.696023, -0.076058]],
  [133, [-0.267199, -0.041800]],
  [168, [-0.000908, -0.130161]],
  [195, [0.000688, 0.198679]],
  [197, [-0.000849, 0.098794]],
  [263, [0.695097, -0.085313]],
  [362, [0.267679, -0.043362]],
  [468, [-0.498778, -0.095054]],
  [473, [0.501214, -0.099269]],
]

/** The mean shape change from neutral to smile, unit-norm over the whole driven
 *  set, with jaw-opening and lip-parting projected out. Multiply by a person's
 *  amplitude and by the commanded fraction to get a canonical displacement.
 *
 *  Mean cosine of an individual smile with this axis: 0.958 --
 *  i.e. real smiles point almost the same way in almost everyone, which is why
 *  the runtime learns each person's smile *size* and not its direction. */
export const SMILE_AXIS: ReadonlyArray<readonly [number, readonly [number, number]]> = [
  [61, [-0.177642, -0.184799]],
  [146, [-0.144065, -0.027199]],
  [91, [-0.110411, 0.041414]],
  [181, [-0.077966, 0.097021]],
  [84, [-0.042105, 0.130170]],
  [17, [0.001166, 0.140510]],
  [314, [0.041614, 0.128093]],
  [405, [0.075603, 0.093689]],
  [321, [0.106745, 0.039653]],
  [375, [0.140342, -0.027524]],
  [291, [0.175286, -0.182044]],
  [409, [0.147587, -0.225303]],
  [270, [0.118652, -0.180926]],
  [269, [0.088024, -0.128560]],
  [267, [0.052922, -0.079812]],
  [0, [0.002473, -0.081445]],
  [37, [-0.048452, -0.079906]],
  [39, [-0.084850, -0.128703]],
  [40, [-0.117811, -0.181638]],
  [185, [-0.148368, -0.227297]],
  [78, [-0.174718, -0.163252]],
  [95, [-0.145218, -0.129780]],
  [88, [-0.122903, -0.072886]],
  [178, [-0.090577, -0.022729]],
  [87, [-0.050348, 0.008621]],
  [14, [0.001065, 0.019196]],
  [317, [0.051851, 0.008151]],
  [402, [0.090540, -0.024749]],
  [318, [0.121839, -0.074588]],
  [324, [0.143518, -0.130156]],
  [308, [0.173025, -0.160884]],
  [415, [0.165669, -0.087165]],
  [310, [0.137048, -0.063732]],
  [311, [0.105317, -0.037719]],
  [312, [0.060692, -0.015868]],
  [13, [0.000665, -0.005927]],
  [82, [-0.059860, -0.016245]],
  [81, [-0.105374, -0.038536]],
  [80, [-0.137936, -0.064820]],
  [191, [-0.167432, -0.088908]],
]

/** Mean canonical mouth shape over the neutral corpus. Fallback rest shape,
 *  used only until the live person's own resting mouth has been observed. */
export const POPULATION_REST: ReadonlyArray<readonly [number, readonly [number, number]]> = [
  [61, [-0.401064, 1.005601]],
  [146, [-0.358295, 1.044250]],
  [91, [-0.302138, 1.081670]],
  [181, [-0.219253, 1.129087]],
  [84, [-0.113394, 1.159980]],
  [17, [0.004588, 1.168660]],
  [314, [0.125455, 1.158539]],
  [405, [0.232124, 1.125550]],
  [321, [0.315815, 1.078477]],
  [375, [0.372294, 1.037085]],
  [291, [0.410392, 0.999894]],
  [409, [0.371660, 0.969178]],
  [270, [0.316475, 0.933827]],
  [269, [0.236780, 0.893988]],
  [267, [0.121344, 0.856521]],
  [0, [0.003959, 0.882327]],
  [37, [-0.113779, 0.858083]],
  [39, [-0.229805, 0.896526]],
  [40, [-0.306782, 0.937758]],
  [185, [-0.361558, 0.973040]],
  [78, [-0.364353, 1.003116]],
  [95, [-0.303788, 1.001380]],
  [88, [-0.249450, 0.997823]],
  [178, [-0.176420, 0.996172]],
  [87, [-0.091615, 0.996339]],
  [14, [0.004833, 1.001768]],
  [317, [0.100936, 0.998181]],
  [402, [0.188847, 0.993046]],
  [318, [0.260219, 0.994444]],
  [324, [0.315743, 0.996777]],
  [308, [0.376231, 0.998235]],
  [415, [0.312210, 0.994781]],
  [310, [0.257679, 0.991008]],
  [311, [0.186389, 0.988934]],
  [312, [0.101015, 0.992581]],
  [13, [0.004517, 0.996506]],
  [82, [-0.090394, 0.992194]],
  [81, [-0.175403, 0.990007]],
  [80, [-0.247828, 0.995521]],
  [191, [-0.303202, 0.999460]],
]

/** Distribution of own-smile amplitude across the corpus, in interpupillary
 *  units of total shape change. The population median is the cold-start gain;
 *  the spread is the size of the problem this project exists to fix. */
export const AMPLITUDE_STATS = {
  mean: 0.642581,
  sd: 0.191346,
  p10: 0.403382,
  p50: 0.642506,
  p90: 0.899090,
  n: 307,
} as const

/** Mean cosine between an individual's smile axis and the population axis. */
export const AXIS_CONSISTENCY = 0.9576
