"""Export the triangle mesh the appearance morph warps over.

The morph warps two images — the live frame and a stored keyframe of the
person's own smile — onto one intermediate geometry, then cross-dissolves. Both
warps must use the *same* topology or the triangles do not correspond and the
blend ghosts. So the triangulation is computed once here, on the corpus-average
canonical face, and shipped as a constant rather than recomputed per frame from
whatever shape happens to be on screen.

Point set covers the lower face, which is where a smile happens: the lips, the
perioral and nasolabial region, the cheeks and the jaw line. Around it sits a
ring of anchor points that never move, so the warp dies out before it reaches
the eyes or the frame edge. The eyes are deliberately excluded — a real smile
does crinkle them, but they are also where a misaligned blend is most obviously
wrong, and the keyframe will rarely share the live frame's gaze.

    .venv/Scripts/python.exe tools/export_mesh.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from scipy.spatial import Delaunay

sys.path.insert(0, str(Path(__file__).parent))
import facegeom as fg  # noqa: E402

HERE = Path(__file__).parent.parent
CACHE = HERE / "artifacts" / "cache" / "cfd_landmarks3d.npz"
OUT_TS = HERE / "src" / "algo" / "morphMesh.gen.ts"

# Everything a smile moves.
MOVING = sorted(set(
    fg.OUTER_LIP + fg.INNER_LIP
    # perioral and nasolabial
    + [205, 425, 216, 436, 192, 416, 57, 287, 212, 432, 202, 422, 204, 424]
    # nose base and alae, which lift and flare
    + [2, 326, 97, 98, 327, 129, 358, 64, 294, 1]
    # cheeks: the malar region that rises
    + [123, 352, 117, 346, 118, 347, 101, 330, 36, 266, 50, 280]
    # jaw and chin
    + [152, 148, 176, 149, 150, 136, 172, 377, 378, 379, 365, 397, 288, 58]
    + [200, 199, 175, 32, 262, 106, 335]
))

# Held fixed, so the deformation decays to nothing before the eyes or the edge
# of the frame.
ANCHORS = sorted(set([
    33, 133, 362, 263, 468, 473,        # eyes
    168, 6, 197, 195, 8,                # nose bridge
    234, 454, 127, 356, 162, 389,       # temples and silhouette
    10, 109, 338, 67, 297, 21, 251,     # forehead and upper silhouette
    132, 361, 93, 323, 227, 447,        # in front of the ears
]))


def main() -> int:
    z = np.load(CACHE, allow_pickle=False)
    ids, exprs, pts = z["ids"], z["exprs"], z["pts"].astype(float)
    neutral = np.where(exprs == "N")[0]

    template = fg.scale_template_to_ipd(
        fg.build_template([pts[i][fg.RIGID_IDX, :2] for i in neutral]))

    # Mean canonical position of every point we care about, over the corpus.
    canon = []
    for i in neutral[:400]:
        f = fg.fit_frame(pts[i], template)
        canon.append(f.to_canonical(pts[i]))
    mean = np.mean(canon, axis=0)

    order = MOVING + [a for a in ANCHORS if a not in MOVING]
    coords = np.array([mean[i] for i in order])

    tri = Delaunay(coords)
    # Drop triangles made entirely of anchors: they cover skin nothing moves,
    # so warping them is wasted work every frame.
    anchor_set = {order.index(a) for a in ANCHORS if a in order}
    tris = [t for t in tri.simplices if not set(t) <= anchor_set]

    def fmt(v: float) -> str:
        return f"{v:.6f}"

    pt_lines = [
        f"  [{order[k]}, [{fmt(coords[k][0])}, {fmt(coords[k][1])}]],"
        for k in range(len(order))
    ]
    tri_lines = [
        "  " + ", ".join(f"[{int(a)}, {int(b)}, {int(c)}]" for a, b, c in tris[i:i + 4]) + ","
        for i in range(0, len(tris), 4)
    ]

    src = f'''// GENERATED by tools/export_mesh.py -- do not edit by hand.
//
// The mesh the appearance morph warps over. Computed once on the corpus-average
// canonical face ({len(neutral)} neutral faces), because both images in a morph
// have to be warped with the SAME topology or their triangles do not correspond
// and the cross-dissolve ghosts.

/** Landmarks the mesh is built from, with their mean canonical positions.
 *  Index into this array is the vertex id used by MESH_TRIANGLES. */
export const MESH_POINTS: ReadonlyArray<readonly [number, readonly [number, number]]> = [
{chr(10).join(pt_lines)}
]

/** How many of the leading MESH_POINTS a smile actually moves. The rest are
 *  anchors, held at their live position so the deformation decays to nothing
 *  before it reaches the eyes or the edge of the frame. */
export const MESH_MOVING_COUNT = {len(MOVING)}

/** Triangles, as triples of indices into MESH_POINTS. Triangles made entirely
 *  of anchors are dropped -- they cover skin that never moves. */
export const MESH_TRIANGLES: ReadonlyArray<readonly [number, number, number]> = [
{chr(10).join(tri_lines)}
]
'''
    OUT_TS.write_text(src, encoding="utf-8")
    print(f"wrote {OUT_TS}")
    print(f"  moving points : {len(MOVING)}")
    print(f"  anchor points : {len(order) - len(MOVING)}")
    print(f"  triangles     : {len(tris)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
